[project]
name = "tsid"
version = "1.6.2.1"
description = "A fast and flexible implementation of Rigid Body Dynamics algorithms and their analytical derivatives"
readme = "README.md"
license= "BSD-3-Clause"
dependencies = ["pin", "eiquadprog"]

[project.urls]
homepage = "https://github.com/stack-of-tasks/tsid"

[tool.cmeel]
build-number = 1
configure-args = ["-DSUFFIX_SO_VERSION=OFF"]

[build-system]
build-backend = "cmeel.build"
requires = [
    "cmeel[build]",
    "cmeel-urdfdom-headers",
    "eiquadprog",
    "pin",
    ]
